# Module `genC2_PR_T_dep_perp_quad` is loaded below 

##  Model data is loaded before this import



---

*Model coefficient :*

Temperature = 299 K


c1 = 0.045

c2 = -0.0150

---

In [1]:
# define the data files to be loaded in the script before importing
import numpy as np
import genC2_PR_T_dep_perp_quad

		 -- TEST SCRIPT --
		 Loaded files:
			 H2 : model_H2_perp_quadratic.exp
			 HD : model_HD_perp_quadratic.exp
			 D2 : model_D2_perp_quadratic.exp
		 ---------------

Dimension of input data
	 (6, 2)
	 (8, 2)
	 (13, 2)
	**********************************************************
	 
	 This module is for generating the wavenumber-dependent
	 intensity correction curve termed as C2 from 
	  experimental Raman intensities using intensity ratios 

	 >> Ratios of all observed Raman intensities are treated here. << 

	 >> Parallel polarized Raman intensities (relative to 
		       incident linearly polarized beam)  << 

	 >> Temperature is a fit parameter << 

	 This modeule requires edit on line 17 to 54 to 

	  load and set parameters for the analysis.
	 
	**********************************************************

		 Checking imported data and set params
		  dataH2 found, OK
		  dataHD found, OK
		  dataD2 found, OK
		  xaxis found, OK

		  Analysis parameters:
		 scaling factors (for c1 

In [2]:
# Running fitting for linear model

genC2_PR_T_dep_perp_quad.run_fit_linear( 299, -1.045)

**********************************************************
Initial coef :  T=299, k1=-1.045 output = 910.3448396029729

Optimization run: Linear     

 final_simplex: (array([[279.27835445,  -0.56633842],
       [279.27835445,  -0.56633842],
       [279.27835445,  -0.56633842]]), array([274.9447309, 274.9447309, 274.9447309]))
           fun: 274.9447309008309
       message: 'Optimization terminated successfully.'
          nfev: 169
           nit: 78
        status: 0
       success: True
             x: array([279.27835445,  -0.56633842])

Optimized result : T=279.27835445, k1=-0.00566338 

**********************************************************


274.9447309008309

In [3]:
# # Running fitting for quadratic model

genC2_PR_T_dep_perp_quad.run_fit_quadratic( 299, -0.285, 0.052)

**********************************************************
Initial coef :  T=299, k1=-0.285, k2=0.052 output = 75.01440207662652

Optimization run: Quadratic     

 final_simplex: (array([[ 2.99e+02,  4.50e-03, -1.50e-04],
       [ 2.99e+02,  4.50e-03, -1.50e-04],
       [ 2.99e+02,  4.50e-03, -1.50e-04],
       [ 2.99e+02,  4.50e-03, -1.50e-04]]), array([1.15174828e-21, 3.14751506e-21, 3.26415705e-21, 3.43831933e-21]))
           fun: 1.1517482839807256e-21
       message: 'Optimization terminated successfully.'
          nfev: 294
           nit: 158
        status: 0
       success: True
             x: array([ 2.99e+02,  4.50e-03, -1.50e-04])

Optimized result : T=299.0, k1=4.5e-05, k2=-0.0 

**********************************************************


1.1517482839807256e-21

In [4]:
# # Running fitting for cubic model

genC2_PR_T_dep_perp_quad.run_fit_cubic( 299, -0.285, 0.052, 0.0)

**********************************************************
Initial coef :  T=299, k1=-0.285, k2=0.052, k3=0.0, output = 75.01440207662652

Optimization run : Cubic     

 final_simplex: (array([[ 2.99000000e+02,  4.50000000e-03, -1.50000000e-04,
         2.58980714e-14],
       [ 2.99000000e+02,  4.50000000e-03, -1.50000000e-04,
         1.66980859e-14],
       [ 2.99000000e+02,  4.50000000e-03, -1.50000000e-04,
        -2.73421406e-14],
       [ 2.99000000e+02,  4.50000000e-03, -1.50000000e-04,
         4.23225154e-14],
       [ 2.99000000e+02,  4.50000000e-03, -1.50000000e-04,
        -4.66251818e-15]]), array([4.94466446e-21, 7.51408713e-21, 1.01093512e-20, 1.05654293e-20,
       1.11064659e-20]))
           fun: 4.944664462547079e-21
       message: 'Optimization terminated successfully.'
          nfev: 551
           nit: 323
        status: 0
       success: True
             x: array([ 2.99000000e+02,  4.50000000e-03, -1.50000000e-04,  2.58980714e-14])

Optimized result : T=299

4.944664462547079e-21

---


In [5]:
print(genC2_PR_T_dep_perp_quad.xaxis)

[2281.1594 2282.5403 2283.9231 ... 4215.3828 4216.4424 4217.5029]


In [6]:
print(genC2_PR_T_dep_perp_quad.xaxis - genC2_PR_T_dep_perp_quad.scenter )

[-1035.1406 -1033.7597 -1032.3769 ...   899.0828   900.1424   901.2029]


In [39]:
scaled_xaxis = (genC2_PR_T_dep_perp_quad.xaxis - genC2_PR_T_dep_perp_quad.scenter ) 


maxV=  np.abs(scaled_xaxis).max()

magn = genC2_PR_T_dep_perp_quad.orderOfMagnitude(np.amax(scaled_xaxis))

print(10**magn)

100


In [40]:
sc=scaled_xaxis / (10**magn)

print(sc, sc.shape)

[-10.351406 -10.337597 -10.323769 ...   8.990828   9.001424   9.012029] (1600,)


In [41]:
print(genC2_PR_T_dep_perp_quad.scale1, genC2_PR_T_dep_perp_quad.scale2,genC2_PR_T_dep_perp_quad.scale3)

100 10000 1000000


---