# Generate $C_2$ from vibration-rotation Raman intensities of $H_{2}$, $HD$ and $D_{2}$


## >> temperaure is a fit variable here <<


## Parallel polarized

## Module `genC2_VR_T_dep_para`

####  Experimental data with corresponding error for H2, HD and D2

| band_area                  | error |
|----------------------------|-------|
| Area for J_max(antiStokes) | err   |
| ...                        | ...   |
| ...                        | ...   |
| Area for J_max (Stokes)    | err   |

Experimental data is in the form of the 2D array : The first column has the band area, while the second column has the error.

The first row has the data for the highest J anti-Stokes band. Following rows contain the area as we move to higher wavenumbers. (This arrangement is strictly required since corresponding reference data is generated in the same order).

#### J_max indices for the band area :
In order for `compute_series_para` program to generate the band area for the same set as the experimental data, the correct J_max value must be supplied in the beginning section of the `genC2_CR_para` program.

This block is given below:


In [1]:
# define the data files to be loaded in the script before importing

import genC2_VR_T_dep_para

Dimension of input data
	 (7, 2)
	 (9, 2)
	 (14, 2)
	**********************************************************
	 
	 This module is for generating the wavenumber-dependent
	 intensity correction curve termed as C2 from 
	  experimental Raman intensities using intensity ratios 

	 >> Ratios of all observed Raman intensities are treated here. << 

	 >> Parallel polarized Raman intensities (relative to 
		       incident linearly polarized beam)  << 

	 >> Temperature is a fit parameter << 

	 This modeule requires edit on line 17 to 54 to 

	  load and set parameters for the analysis.
	 
	**********************************************************

		 Checking imported data and set params
		  dataH2 found, OK
		  dataHD found, OK
		  dataD2 found, OK
		  xaxis found, OK

		  Analysis parameters:
		 scaling factors (for c1 to c3) 100 10000 1000000
		 Norm (defn of residual):  Frobenius
	**********************************************************

	 REQUIRED DATA
			 Ramanshift = vector, the

In [2]:
# Running fitting for linear model

In [3]:
genC2_VR_T_dep_para.run_fit_linear(296,  -0.6 )

# function returns the residual value


**********************************************************
		 -- Linear fit -- 
		Norm (defn of residual):  Frobenius
Initial coef :  T=296, k1=-0.6 output = 21.366884394559804

Optimization run: Linear     

 final_simplex: (array([[282.79623615,  -0.58098725],
       [282.79623615,  -0.58098725],
       [282.79623616,  -0.58098725]]), array([21.19718988, 21.19718988, 21.19718988]))
           fun: 21.197189877217696
       message: 'Optimization terminated successfully.'
          nfev: 149
           nit: 68
        status: 0
       success: True
             x: array([282.79623615,  -0.58098725])

Optimized result : T=282.796236, k1=-0.580987 

**********************************************************


21.197189877217696

In [4]:
genC2_VR_T_dep_para.run_fit_quadratic(296,  -0.6 , 0.001 )

**********************************************************
		 -- Quadratic fit -- 
		Norm (defn of residual):  Frobenius
Initial coef :  T=296, k1=-0.6, k2=0.001 output = 21.203749762202275

Optimization run: Quadratic     

 final_simplex: (array([[ 2.81871031e+02, -6.02216754e-01,  5.53889654e-02],
       [ 2.81871031e+02, -6.02216754e-01,  5.53889654e-02],
       [ 2.81871031e+02, -6.02216754e-01,  5.53889654e-02],
       [ 2.81871031e+02, -6.02216754e-01,  5.53889654e-02]]), array([9.41485442, 9.41485442, 9.41485442, 9.41485442]))
           fun: 9.41485442194637
       message: 'Optimization terminated successfully.'
          nfev: 347
           nit: 179
        status: 0
       success: True
             x: array([ 2.81871031e+02, -6.02216754e-01,  5.53889654e-02])

Optimized result : T=281.871031, k1=-0.602217, k2=0.055389 

**********************************************************


9.41485442194637

In [5]:
# J levels are defined for the O, Q and S bands


OJ_H2 = 3
QJ_H2 = 4

OJ_HD = 3
QJ_HD = 3
SJ_HD = 2

OJ_D2 = 4
QJ_D2 = 6
SJ_D2 = 3


---


### [See example](https://github.com/ankit7540/IntensityCalbr/blob/master/PythonModule/determine_C2/vibration_rotation_H2_HD_D2/common_rotational_state/Examples/example_compute_series.ipynb) for computation of reference Raman intensities for vibration-rotation transitions at a temperature.

In [6]:
import compute_series_para
import boltzmann_popln as bp


# defining indices for the J_max for each transition
OJ_H2 = 3
QJ_H2 = 4

OJ_HD = 3
QJ_HD = 3
SJ_HD = 2

OJ_D2 = 4
QJ_D2 = 6
SJ_D2 = 3


sHD=compute_series_para.spectra_HD(299, OJ_HD, QJ_HD, SJ_HD, bp.sumofstate_HD(299))
print(sHD)
print(sHD.shape)

[[3.00000000e+00 3.18522300e+03 7.71333268e-03 1.56047620e+04]
 [2.00000000e+00 3.36509120e+03 1.36967880e-02 1.54248938e+04]
 [3.00000000e+00 3.60911310e+03 3.80203882e-01 1.51808719e+04]
 [2.00000000e+00 3.62061020e+03 9.65431551e-01 1.51693748e+04]
 [1.00000000e+00 3.62830440e+03 1.36412765e+00 1.51616806e+04]
 [0.00000000e+00 3.63216040e+03 6.79702367e-01 1.51578246e+04]
 [0.00000000e+00 3.88767940e+03 3.54957782e-02 1.49023056e+04]
 [1.00000000e+00 4.05219450e+03 3.73872312e-02 1.47377905e+04]
 [2.00000000e+00 4.20995900e+03 2.04598728e-02 1.45800260e+04]]
(9, 4)


In [7]:
sD2=compute_series_para.spectra_D2(299, OJ_D2, QJ_D2, SJ_D2, bp.sumofstate_D2(299))
print(sD2)
print(sD2.shape)

[[4.00000000e+00 2.57264490e+03 6.84562667e-03 1.62173401e+04]
 [3.00000000e+00 2.69397320e+03 6.84706114e-03 1.60960118e+04]
 [2.00000000e+00 2.81455000e+03 1.64509938e-02 1.59754350e+04]
 [6.00000000e+00 2.94975880e+03 2.03550263e-02 1.58402262e+04]
 [5.00000000e+00 2.96219340e+03 4.57248215e-02 1.58277916e+04]
 [4.00000000e+00 2.97261410e+03 3.04296103e-01 1.58173709e+04]
 [3.00000000e+00 2.98098930e+03 3.66411922e-01 1.58089957e+04]
 [2.00000000e+00 2.98729340e+03 1.22836857e+00 1.58026916e+04]
 [1.00000000e+00 2.99150700e+03 6.56099473e-01 1.57984780e+04]
 [0.00000000e+00 2.99361710e+03 5.68346097e-01 1.57963679e+04]
 [0.00000000e+00 3.16636050e+03 3.02664375e-02 1.56236245e+04]
 [1.00000000e+00 3.27852310e+03 1.88406598e-02 1.55114619e+04]
 [2.00000000e+00 3.38726260e+03 2.80104175e-02 1.54027224e+04]
 [3.00000000e+00 3.49209360e+03 7.12657028e-03 1.52978914e+04]]
(14, 4)


---

In [8]:
sH2=compute_series_para.spectra_H2_c(299, OJ_H2, QJ_H2 , bp.sumofstate_H2(299))
print(sH2)
print(sH2.shape)

[[3.00000000e+00 3.56822170e+03 7.41818352e-03 1.52217633e+04]
 [2.00000000e+00 3.80679300e+03 6.46809032e-03 1.49831920e+04]
 [4.00000000e+00 4.10258190e+03 1.59092821e-02 1.46874031e+04]
 [3.00000000e+00 4.12587260e+03 3.39418875e-01 1.46641124e+04]
 [2.00000000e+00 4.14346530e+03 4.32842694e-01 1.46465197e+04]
 [1.00000000e+00 4.15525370e+03 2.42057027e+00 1.46347313e+04]
 [0.00000000e+00 4.16116620e+03 4.62078362e-01 1.46288188e+04]]
(7, 4)


---

## Perpendicular polarization

In [9]:
# define the data files to be loaded in the script before importing

import genC2_VR_T_dep_perp

Dimension of input data
	 (6, 2)
	 (8, 2)
	 (13, 2)
	**********************************************************
	 
	 This module is for generating the wavenumber-dependent
	 intensity correction curve termed as C2 from 
	  experimental Raman intensities using intensity ratios 

	 >> Ratios of all observed Raman intensities are treated here. << 

	 >> Parallel polarized Raman intensities (relative to 
		       incident linearly polarized beam)  << 

	 >> Temperature is a fit parameter << 

	 This modeule requires edit on line 17 to 54 to 

	  load and set parameters for the analysis.
	 
	**********************************************************

		 Checking imported data and set params
		  dataH2 found, OK
		  dataHD found, OK
		  dataD2 found, OK
		  xaxis found, OK

		  Analysis parameters:
		 scaling factors (for c1 to c3) 100 10000 1000000
		 Norm (defn of residual):  Frobenius
	**********************************************************

	 REQUIRED DATA
			 Ramanshift = vector, the